In [1]:
#using array method
import numpy as np
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
type(nums_array)

numpy.ndarray

In [2]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]
nums_2d = np.array([row1, row2, row3])
nums_2d.shape

(3, 3)

In [3]:
#using arrange method
nums_arr = np.arange(5,11)
print(nums_arr)

[ 5  6  7  8  9 10]


In [4]:
nums_arr = np.arange(5,12,2)
print(nums_arr)

[ 5  7  9 11]


In [5]:
#using ones method
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [6]:
ones_array = np.ones((6,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#using zeroes method
zeros_array = np.zeros(6)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


In [8]:
zeros_array = np.zeros((6,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
#using eyes method
eyes_array = np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
#using random rand method
uniform_random = np.random.rand(4,5)
print(uniform_random)

[[0.05052911 0.3648792  0.63813839 0.29314422 0.32531986]
 [0.6505372  0.89700599 0.31973365 0.67250863 0.13098439]
 [0.81270925 0.74377073 0.63457844 0.8151794  0.3750912 ]
 [0.68652803 0.50435982 0.95399121 0.17078665 0.57074338]]


In [12]:
normal_random = np.random.randn(4,5)
print(normal_random)

[[ 0.72788291 -0.59656854  0.92881293  1.08868953  1.9193148 ]
 [ 0.83926081  0.58683466 -0.47129629  1.13518588 -0.05897173]
 [-0.99200782  2.35399353  1.46877744 -1.16059162  1.35635394]
 [-0.20550493 -0.05415069 -0.20296675 -1.67901488  1.55083604]]


In [13]:
integer_random = np.random.randint(10,50,5)
print(integer_random)

[44 49 24 47 47]


In [14]:
#Reshaping numpy arrays
uniform_random = np.random.rand(4,6)
uniform_random = uniform_random.reshape(3,8)
print(uniform_random)

[[0.77851851 0.65200019 0.57849317 0.63348531 0.97168464 0.20686721
  0.52543007 0.55007948]
 [0.84912704 0.51960163 0.08174837 0.6370909  0.26416582 0.52877784
  0.81194846 0.45221943]
 [0.7410344  0.5187222  0.9083829  0.50401175 0.56178012 0.482188
  0.36979633 0.20918933]]


In [15]:
#Array indexing and slicing
s = np.arange(1,11)
print(s)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
print(s[1])

2


In [17]:
print(s[1:9])

[2 3 4 5 6 7 8 9]


In [18]:
print(s[:5])
print(s[5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [19]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]
nums_2d = np.array([row1,row2,row3])
print(nums_2d[:2,:])

[[10 12 13]
 [45 32 16]]


In [20]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]
nums_2d = np.array([row1,row2,row3])
print(nums_2d[:,:2])

[[10 12]
 [45 32]
 [45 32]]


In [21]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]
nums_2d = np.array([row1,row2,row3])
print(nums_2d[1:,1:])

[[32 16]
 [32 16]]


In [22]:
#Finding square roots
nums = [10,20,30,40,50]
np_sqr = np.sqrt(nums)
print(np_sqr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [23]:
#Finding logs
nums = [10,20,30,40,50]
np_log = np.log(nums)
print(np_log)

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [24]:
#Finding exponents
nums = [10,20,30,40,50]
np_exp = np.exp(nums)
print(np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


In [25]:
#Finding sine and cosine
nums = [10,20,30,40,50]
np_sine = np.sin(nums)
print(np_sine)
np_cos = np.cos(nums)
print(np_cos)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


In [26]:
#Finding matrix dot product
A = np.random.randn(4,5)
B = np.random.randn(5,4)
Z = np.dot(A,B)
print(Z)

[[-0.11923618  0.53528532  3.12250845  2.43151144]
 [ 2.33216762  0.62009425  1.37107098  2.37880712]
 [ 2.23935598  1.52039662  0.01007628  1.77715325]
 [-0.34787074  0.62346234  2.10918787  1.79386675]]


In [28]:
#Element wise matrix multiplication
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]
nums_2d = np.array([row1,row2,row3])
multiply = np.multiply(nums_2d,nums_2d)
print(multiply)

[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


In [29]:
#Finding matrix inverse
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]
nums_2d = np.array([row1,row2,row3])
inverse = np.linalg.inv(nums_2d)
print(inverse)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [30]:
#Finding matrix determinant
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]
nums_2d = np.array([row1,row2,row3])
determinant = np.linalg.det(nums_2d)
print(determinant)

-9.51619735392994e-16


In [31]:
#Finding matrix trace
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]
nums_2d = np.array([row1,row2,row3])
trace = np.trace(nums_2d)
print(trace)

15
